/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'eventDate' : Time,
});
export const BusinessInfo = IDL.Record({
  'yearsExperience' : IDL.Nat,
  'name' : IDL.Text,
  'customersServed' : IDL.Nat,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'eventDate' : Time,
  });
  const BusinessInfo = IDL.Record({
    'yearsExperience' : IDL.Nat,
    'name' : IDL.Text,
    'customersServed' : IDL.Nat,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [], []),
  });
};

export const init = ({ IDL }) => { return []; };